### ISSUE TITLE
[BUG][MazPhoneNumberInput]

### ISSUE THREAD

**Issue by sebestenyb** [LouisMazel/maz-ui#105]
**Describe the bug**
Setting an initial phone number in international format results the country code doubled up, it's displayed in both the country selector list and the input field.

**To Reproduce**
```
<template>
    <div>
        <MazPhoneNumberInput v-model="phoneNumberExample" />
    </div>
</template>

<script>
import {MazPhoneNumberInput} from 'maz-ui';
import "maz-ui/lib/css/base.css";
import "maz-ui/lib/css/maz-phone-number-input.css";

export default {
    props: ['value'],
    components: {MazPhoneNumberInput},
    data() {
        return {
            phoneNumberExample: '+642101234567',
        }
    }
}
```
**Expected behavior**
The input field component should not contain the country code.

**Screenshots**

![Screen Shot 2020-09-28 at 2 49 24 PM](https://user-images.githubusercontent.com/743212/94382778-7685be80-019a-11eb-9321-a58f38bf98ce.png)

**Comment by arnaudbroes** [comment]
I second this!

**Comment by LouisMazel** [comment]
@sebestenyb @arnaudbroes 

I agree with you.

For many reasons and because it causes bugs I can't do this... It causes bugs with the "AsYouType" feature of libphonenumber-js (especially with Russian numbers). If I do this I have to turn off the "AsYouType" feature (number formatting when the user enters their phone number).

I don't have a better choice. If you have any idea how to solve this, I would love to read one of your PRs and have you as a contributor :)

Otherwise, you must provide a phone number without a calling code (+33, +32, etc) AND a country code (FR, BE, DE, etc.)

**Comment by Cromywell** [comment]
quelqu'un sais comment modifier le background de MazPhoneNumberInput ?

**Comment by LouisMazel** [comment]
@Cromywell Set the CSS variable like this :

```html
<MazPhoneNumberInput style="--maz-color-bg: red;" />
```
