### ISSUE TITLE
Loading custom styles

### ISSUE THREAD

**Issue by yormy** [LouisMazel/maz-ui#149]
Your documentation mentions: 

`The CSS file is generated where you requested it (output), now import it in your applicaton (must be load after maz-ui CSS/SCSS files)`

However when I follow your instructions I do not include the css/scss manually, just using your babel config.
I am having an app.scss root, and when I include the generated root.scss that style is not reflected on my screen

Any ideas

**Comment by LouisMazel** [comment]
Hi @yormy 

Where you import your `app.scss` ?

You can follow this example : 
- DEMO : [https://louismazel.github.io/maz-ui-test/](https://louismazel.github.io/maz-ui-test/)
- GITHUB : [https://github.com/LouisMazel/maz-ui-test](https://github.com/LouisMazel/maz-ui-test)

In this demo, the button is red because the [`_root-variables.css`](https://github.com/LouisMazel/maz-ui-test/blob/master/src/assets/_root-variables.css) is imported by the [`/plugins/maz-ui/index.js`](https://github.com/LouisMazel/maz-ui-test/blob/master/src/plugins/maz-ui/index.js)

It's works fine with [`babel.config.js`](https://github.com/LouisMazel/maz-ui-test/blob/master/babel.config.js)

**Comment by yormy** [comment]
Awesome

import Vue from "vue";
import { MazBtn, MazGallery } from "maz-ui";
===> import "./../../assets/_root-variables.css";

That was the one I was missing,
Please include that in your documentation at the section "Now import component as you want"
```
import Vue from 'vue'
import { MazBtn, MazInput } from 'maz-ui'
// optionally , import your custom style sheet
//  import "./../../assets/_root-variables.css";
```
