### ISSUE TITLE
Maz-ui by default does not include the styles

### ISSUE THREAD

**Issue by roselily8** [LouisMazel/maz-ui#157]
Hi,

Can you please try to create nuxt project with maz-ui and purgecss. It seems the css are not by default included when using purgecss. Is this a bug?

Thanks,

**Comment by LouisMazel** [comment]
@roselily8 

Are you using the babel config as explained in the [Get Started](https://louismazel.github.io/maz-ui/documentation/get-started) ?
With this configuration and the partial import, Babel will automatically import the JS and the style

---

Otherwise, you have to import the component and his CSS like that : 

```js
import MazPhoneNumberInput from "maz-ui/lib/maz-phone-number-input";
import "maz-ui/lib/css/base.css";
import "maz-ui/lib/css/maz-phone-number-input.css";
```

--> [codesandbox example](https://codesandbox.io/s/mazphonenumberinput-gjfsd?file=/src/App.vue:367-521)

If you are using multiple components, import the `base.css` file only once

**Comment by roselily8** [comment]
Hi Maz,

I did follow the startup guide. Here is our nuxt.config.js

plugins: ["~/plugins/maz-ui"],


      compact: true,
      plugins: [
        [
          "component",
          {
            libraryName: "element-ui",
            styleLibraryName: "theme-chalk",
          },
          "element-ui",
        ],
        [
          "component",
          {
            libraryName: "maz-ui",
            styleLibraryName: "css",
          },
          "maz-ui",
        ],
      ],
    },

**Comment by LouisMazel** [comment]
Hi @roselily8 , 

Please try this : 

```js
plugins: [
   [
    "component",
    {
      libraryName: "element-ui",
      styleLibraryName: "theme-chalk",
    },
  ],
  [
    'component',
    {
      libraryName: 'maz-ui',
      styleLibraryName: 'css'
    }
  ]
]
```
