### ISSUE TITLE
MazPicker future year not working

### ISSUE THREAD

**Issue by alexauvray** [LouisMazel/maz-ui#184]
https://user-images.githubusercontent.com/28756458/131889544-84a715d6-c019-4150-992b-04a4291a8aea.mov

Picking date on Maz Picker doesn't work anymore on 2.3.9. Had to downgrade to make it work again.

**Comment by LouisMazel** [comment]
Hello @alexauvray,

It's a normal behavior : 
- The year selector must not change the selected date 
- The year selector change the current year of the date area of selection

So : 
- You have to select the year
- And select the date in the date picker
- Then, change the time of the current date previously selected

You have the same behavior here : https://element.eleme.io/#/fr-FR/component/datetime-picker

Otherwise you can use a DatePicker and in other input a TimePicker
