### ISSUE TITLE
[BUG][MazPhoneNumberInput] Removing or adding characters in the middle of the string jumps the cursor to the end

### ISSUE THREAD

**Issue by Muntrue** [LouisMazel/maz-ui#196]
When you want to modify a phone number by removing or adding characters in the middle, it will jump the cursor to the end of the string after modification

1. Enter a number into the phone-number field (ex: 1234567)
2. Move the cursor to the number 4 in the string and hit backspace
3. The cursor will automatically move back to the end of the string.

**Expected behavior**
The cursor should remain on the users selected position after modification.

**Desktop (please complete the following information):**

- OS: Windows 11, Windows 10
- Browser: Chrome, Edge, Firefox
- Version: Does not seem applicable

**Comment by LouisMazel** [comment]
Hi @Muntrue 

Which version of `maz-ui` do you use ? 

Thanks

**Comment by Muntrue** [comment]
Hi @LouisMazel 
Currently using version 2.3.12 

I see the same behavior happen on the official documentation page https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input/

If you need further input, i will be happy to provide!

**Comment by LouisMazel** [comment]
Thanks for the informations. 

I'm currently working on the [Vue 3 version](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html#basic-usage) and I see the same bad behavior.

It's because of the `AsYouType` feature from `libphonenumber-js`. It rewrites the whole string, so the cursor position is lost.

I will investigate and try to fix it on both version (2.x & 3.x). 

I will give to you an update here when it's done (or not).

**Comment by LouisMazel** [comment]
@Muntrue 

Solved in both version: 

- Vue 2 : [Release - maz-ui@v2.3.13](https://github.com/LouisMazel/maz-ui/releases/tag/v2.3.13)
- Vue 3 : maz-ui@3.0.0-next.1

Enjoy
