### ISSUE TITLE
MazPhoneNumberInput

### ISSUE THREAD

**Issue by RonnieMamangunQx** [LouisMazel/maz-ui#333]
I am using MazPhoneNumberInput I want the input field to accept numbers only but when I type the characters it was accepted.
Is there any options/props I need to set?

![image](https://user-images.githubusercontent.com/76149105/184108040-645d3b23-c0d3-4077-b833-0d22d337d7b8.png)

**Comment by LouisMazel** [comment]
Hi @RonnieMamangunQx,

I will not fix this issue because it the default behavior of the `<input type="tel" />`

In this library, I wan't override the native behavior of HTML Elements because : 
- The behavior will not be the good for all users and devs
- The letters are deleted on blur or keydown events
- It's too much complexe to filter between letters and special characters allowed

Thanks for your issue
