### ISSUE TITLE
[Issue][<COMPONENT>]

### ISSUE THREAD

**Issue by parsagholipour** [LouisMazel/maz-ui#473]
Importing `css/main.css` overwrites styles.
`*,:after,:before{border:0 solid;}`
is making borders colors black(initial).
![Screenshot (104)](https://user-images.githubusercontent.com/57809920/209445249-918331ff-17c9-4241-a835-110abd8f29c9.png)
and is overwriting the border colors I set on `*`.
Using `border-style: solid; border-width: 0` doesn't produce the same thing.

**Comment by LouisMazel** [comment]
Hey @parsagholipour,

I think your CSS rules are overridden because maz-ui's CSS is loaded after your CSS.
You must import `maz-ui/css/main.css` before your own CSS. 

Check this doc: [Getting Started - Import Necessary CSS File](https://louismazel.github.io/maz-ui-3/guide/getting-started#import-necessary-css-file)

**Comment by parsagholipour** [comment]
@LouisMazel I'm using Nuxt 3 and added mazui css at `defineNuxtConfig`. I'm using Windicss and have no control over the css.
Fixed this by changing the file: `border: 0 solid` to `border-style: solid; border-width: 0`
