### ISSUE TITLE
overflow-x on MazCarousel

### ISSUE THREAD

**Issue by Timothy16** [LouisMazel/maz-ui#479]
I suggest that overflow-x should be hidden 
![image](https://user-images.githubusercontent.com/55112043/212295631-0bd54abc-cfc7-454e-ac4d-21792d05cb39.png)

**Comment by LouisMazel** [comment]
Hey @Timothy16, 

If you do that, the user can no longer scroll in carousel on mobile or with the trackpad on desktop. He could just use the arrows and it's a big limitation and a bad UX.  

If you want just hide the scrollbar (I don't want do it myself in the component for the accessibility and the UX), you can use something like that: 

```vue
<template>
  <MazCarousel class="carousel" images="[]" />
</template>
 
<style scoped>
  .carousel >>> .m-carousel__items::-webkit-scrollbar {
    display: none;
  }
</style>
```

You can use the `:deep()` selector instead of `>>>`

**Comment by Timothy16** [comment]
Thank you @LouisMazel this worked for me.
