### ISSUE TITLE
Css is not loading MazPhoneNumberInput

### ISSUE THREAD

**Issue by kagankorkmaz** [LouisMazel/maz-ui#50]
Inside the template: 
`           <MazPhoneNumberInput v-model="myForm.contactPhone"/>
`

and in the script:

```
import { MazPhoneNumberInput } from 'maz-ui' 

export default {
    name: "Institution",
    components: {
        // VuePhoneNumberInput: VuePhoneNumberInput,
        MazPhoneNumberInput
    }
}
```

But the css of the compnenet is not loading

**Comment by Warchiefs** [comment]
How are you resolve it?

**Comment by LouisMazel** [comment]
It's solved ? 

You must use babel as described here to automatically import the styling files: [Get Started Documentation](https://louismazel.github.io/maz-ui/documentation/get-started)

Otherwise, you can import manually the style like this: 

```js
import { MazPhoneNumberInput } from "maz-ui";
import "maz-ui/lib/css/base.css";
import "maz-ui/lib/css/maz-phone-number-input.css";
```

Example in this codesanbox: https://codesandbox.io/s/mazphonenumberinput-ekyd8?file=/src/App.vue:1047-1186

**Comment by kagankorkmaz** [comment]
Thanks for your response, I decided to use another component. It was easier to use in terms of understanding css, html hierarchy and manipulate the css. Thanks for your help.
