### ISSUE TITLE
[QUESTION] Changing default css stylings.

### ISSUE THREAD

**Issue by kagankorkmaz** [LouisMazel/maz-ui#51]
Is it possible to change default css values without changing .babelrc or vue.config.js since ı am in a big project and these files are in different format and pretty complicated. Also ı would like to say that like in the your vuePhoneNumberInput component colors so easy to change. It would be nice to add these options as a prop like font-weight, font-size, colors, border-radius-border-width.

**Comment by LouisMazel** [comment]
Hi @kagankorkmaz,

No, this is technically not possible because you have to load the SCSS files to change the variables.

Otherwise, you can create a CSS file to override the CSS properties

In the future I will make a theme generator to build all the CSS files with your colors but that is not yet for now. 

I open a way out for that: https://github.com/LouisMazel/maz-ui/issues/53
