### ISSUE TITLE
Module not found: Error: Default condition should be last one in vue 3

### ISSUE THREAD

**Issue by jfnando3030** [LouisMazel/maz-ui#627]
when use: 
import MazPhoneNumberInput from 'maz-ui/components/MazPhoneNumberInput'
app.component('MazPhoneNumberInput', MazPhoneNumberInput)

I get the following error:
Module not found: Error: Default condition should be last one

I am using version ^3.12.2

**Comment by LouisMazel** [comment]
Hi @jfnando3030,

I can't reproduce it with a vue 3 fresh app (using `npm create vue@latest`). All work fine with it.

But I released some new changes to the declaration modules, can you try the **[v3.13.0](https://github.com/LouisMazel/maz-ui/releases/tag/v3.13.0)**? 
Let me know if the issue is fixed. 

Thanks for your feedback!

**Comment by jfnando3030** [comment]
yes, the bug was fixed

thank you very much
